#ifndef _SMARTRF_SETTINGS_H_
#define _SMARTRF_SETTINGS_H_

#ifndef RF_PREAMBLE_BYTES
#define RF_PREAMBLE_BYTES            0x4
#endif

//*********************************************************************************
// Generated by SmartRF Studio version 2.6.0 (build #81)
// Tested for SimpleLink SDK version: CC13x0 SDK 1.0.xx
// Device: CC1350 Rev. 2.1
//
//*********************************************************************************

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>


// TI-RTOS RF Mode Object
extern RF_Mode RF_prop;

// RF Core API commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_PROP_RX_ADV_t cmdRx;
extern rfc_CMD_PROP_TX_ADV_t cmdTx;
extern volatile rfc_CMD_RX_TEST_t RF_cmdRxTest;
extern rfc_CMD_TX_TEST_t RF_cmdTxTest;
extern rfc_CMD_PROP_CS_t cmdPropCs;
extern rfc_CMD_COUNT_BRANCH_t cmdCountBranch;
extern rfc_CMD_NOP_t cmdNop;
extern rfc_CMD_PROP_RX_ADV_SNIFF_t RF_cmdPropRxAdvSniff;
extern uint32_t pOverrides[];
extern uint32_t pOverrides868[];

#endif /* SMARTRF_SETTINGS_SMARTRF_SETTINGS_H_ */
